[build]
  command = "pip install -r requirements.txt"
  publish = "static"

[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  included_files = [
    "netlify/functions/**",
    "requirements.txt"
  ]

# Python runtime for functions
[functions."app"]
  runtime = "python3.9"

[[redirects]]
  from = "/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true